### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [nemeshnorbert/pedantic-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by nemeshnorbert** [comment]
@unixorn I've already added a license [here](https://github.com/nemeshnorbert/pedantic-zsh-theme/blob/master/LICENSE).
This theme is still WIP as I want to integrate a comprehensive git status. 

It works fine as is right now. As git status prompt will be complete I will add a screenshot.

**Comment by unixorn** [comment]
Ok, close this once you're ready for it to appear in the list and I'll add it, or you can PR it in yourself.

**Comment by nemeshnorbert** [comment]
@unixorn, theme is complete. You can use it if you like it
